projects/urls.py
from django.conf.urls import url
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category', views.CategoryListView.as_view(), name='category-list'),
    path('challenge', views.ChallengeListView.as_view(), name='challenge-list'),
    path('project/by-category/<slug:slug>', views.ProjectByCategoryListView.as_view(), name='project-list-by-category'),
    path('project/by-challenge/<slug:title>', views.ProjectByChallengeListView.as_view(), name='project-list-by-challenge'),
]

wvc/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from projects.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login', auth_views.LoginView.as_view(), name="login"),
    path('logout', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name="logout"),
    path('', IndexView.as_view(), name='index'),
    path('projects/', include('projects.urls', namespace='projects')),
]

projects/models.py
from django.db import models
from django.conf import settings

class Challenge(models.Model):
    slug = models.SlugField(max_length=32, unique=True)
    title = models.CharField(max_length=255)

    def __repr__(self):
        return("Challenge(title={})".format(self.title))

    def __str__(self):
        return(self.title)

class SlackChannel(models.Model):
    name = models.CharField(max_length=255)
    
    def __repr__(self):
        return("ClackChannel(name={})".format(self.name))

    def __str__(self):
        return(self.name)


class Category(models.Model):
    slug = models.SlugField(max_length=32, unique=True)
    description = models.CharField(max_length=255)

    def __repr__(self):
        return("Category(slug={}, description={})".format(self.slug, self.description))

    def __str__(self):
        return(self.slug)


class Project(models.Model):
    title = models.CharField(max_length=255)
    challenge = models.ForeignKey(Challenge, on_delete=models.PROTECT)
    problem = models. TextField()
    explanation = models. TextField()
    idea = models.TextField()
    affected = models.TextField()
    stakeholder = models.TextField()
    category = models.ManyToManyField(Category)
    slack = models.ForeignKey(SlackChannel, on_delete=models.PROTECT)

    def __str__(self):
        return(self.title)

class Preference(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL ,on_delete=models.PROTECT)
    project = models.ForeignKey(Project, on_delete=models.PROTECT)
    value = models.IntegerField()

projects/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from .models import Category, Challenge, Project

class IndexView(TemplateView):
    template_name = "projects/index.html"


class CategoryListView(ListView):
    model = Category

class ChallengeListView(ListView):
    model = Challenge

class ProjectByCategoryListView(ListView):
    model = Project

class ProjectByChallengeListView(ListView):
    model = Project

projects/templates/projects/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
{% block head %}
<head>
    <meta charset="UTF-8">
    {% block title %}<title>{% trans '#WwirVsVirus' %} - {% trans 'Landing Page' %}</title>{% endblock %}
    <link rel="stylesheet" href="/static/application/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/static/application/css/apply.css"/>
    {% block header_additional %}{% endblock %}
</head>
{% endblock %}
{% block body %}
<body>
{% block content_wrapper %}
<div class="container card mt-3 mb-5">
    <div class="card-body">
        {% block content %}
        <h1>Default page</h1>
        This default pages has no content.
        {% endblock %}
    </div>
</div>
{% endblock %}
{% endblock %}
</body>
</html>

projects/templates/projects/category_list.html
{% extends 'projects/base.html' %}
{% load i18n %}
{% block header_additional %}
<style>
	body {background-color: white;}
	table {border-collapse: collapse;}
	th {background-color: #444;color: white;}
	tr:nth-child(even) {background-color: #f2f2f2;}
	tr {border-bottom: solid 1px #ddd;}
	tr:last-of-type {border-bottom: none}
	td,th {border-left: solid 1px #888;border-right: solid 1px #888;}
	th:first-of-type {border-left: none;}
	th:last-of-type {border-right: none;}
	td:first-of-type {border-left: none;}
	td:last-of-type {border-right: none;}
</style>
{% endblock %}
{% block content %}
<table>
	<thead>
		<tr>
			<th><Name/th>
		</tr>
	</thead>
	<tbody>
{% for object in object_list %}
	<tr>
		<td><a href="{% url 'projects:project-list-by-category' object.slug %}">{{ object.description }}</a></td>
{% empty %}
	<tr><td colspan="9">{% trans 'There are no categories' %}</td></tr>
{% endfor %}
	</tbody>
</table>
{% endblock %}

projects/templates/projects/challenge_list.html
{% extends 'projects/base.html' %}
{% load i18n %}
{% block header_additional %}
<style>
	body {background-color: white;}
	table {border-collapse: collapse;}
	th {background-color: #444;color: white;}
	tr:nth-child(even) {background-color: #f2f2f2;}
	tr {border-bottom: solid 1px #ddd;}
	tr:last-of-type {border-bottom: none}
	td,th {border-left: solid 1px #888;border-right: solid 1px #888;}
	th:first-of-type {border-left: none;}
	th:last-of-type {border-right: none;}
	td:first-of-type {border-left: none;}
	td:last-of-type {border-right: none;}
</style>
{% endblock %}
{% block content %}
<table>
	<thead>
		<tr>
			<th><Name/th>
		</tr>
	</thead>
	<tbody>
{% for object in object_list %}
	<tr>
		<td><a href="{% url 'projects:project-list-by-challenge' object.slug %}">{{ object.title }}</a></td>
{% empty %}
	<tr><td colspan="9">{% trans 'There are no categories' %}</td></tr>
{% endfor %}
	</tbody>
</table>
{% endblock %}

projects/templates/projects/index.html
{% extends 'projects/base.html' %}
{% load i18n %}
{% block content %}
	<h1>{% trans '#WirVsVirus - Auswahlhilfe' %}</h1>
{% endblock %}

projects/templates/projects/project_list.html
{% extends 'projects/base.html' %}
{% load i18n %}
{% block header_additional %}
<style>
	body {background-color: white;}
	table {border-collapse: collapse;}
	th {background-color: #444;color: white;}
	tr:nth-child(even) {background-color: #f2f2f2;}
	tr {border-bottom: solid 1px #ddd;}
	tr:last-of-type {border-bottom: none}
	td,th {border-left: solid 1px #888;border-right: solid 1px #888;}
	th:first-of-type {border-left: none;}
	th:last-of-type {border-right: none;}
	td:first-of-type {border-left: none;}
	td:last-of-type {border-right: none;}
</style>
{% endblock %}
{% block content %}
{% for object in object_list %}
<div class="project">
	<h1>{{ object.title }}</h1>
	<p><h2>Probleme</h2><br>{{ object.problem }}</p>
	<p><h2>Herausforderung</h2><br>{{ object.explanation }}</p>
	<p><h2>Lösungsansatz</h2><br>{{ object.idea }}</p>
	<p><h2>Betroffenengruppe</h2><br>{{ object.affected }}</p>
	<p><h2>Stakeholder</h2><br>{{ object.stakeholder }}</p>
	<p><h2>Slack-Channel</h2><br>{{ object.slack }}</p>
	<p><h2>Kategorien</h2><br>{{ object.category }}</p>

</div>
{% empty %}
<p>{% trans 'There are no projects available' %}</p>
{% endfor %}
{% endblock %}